# Decision Tree using Scikit Learn

In [72]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import tree
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
import matplotlib.pyplot as plt

In [76]:
def train_test_validation_split(x: pd.DataFrame, y: pd.Series, train_size: float, test_size: float, validation_size: float) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.Series, pd.Series, pd.Series]:
    x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=train_size, test_size=test_size + validation_size)
    x_test, x_validation, y_test, y_validation = train_test_split(x_test, y_test, train_size=test_size / (test_size + validation_size), test_size=validation_size / (test_size + validation_size))
    return x_train, x_test, x_validation, y_train, y_test, y_validation

In [78]:
df = pd.read_csv('Vectores_Caracteristicos_Mariposas.csv')
x = df.drop('Etiqueta', axis=1)
y = df['Etiqueta']
set
# 70 % para entrenamiento, 15 % para validacion y 15 % para testing
x_train, x_test, x_validation, y_train, y_test, y_validation = train_test_validation_split(x, y, train_size=0.7, test_size=0.15, validation_size=0.15)

clf = DecisionTreeClassifier(criterion="entropy")
clf.fit(x_train,y_train)
clf.score(x_test,y_test)
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))
print(precision_score(y_test, clf.predict(x_test), average='macro'))

# tree.plot_tree(clf, filled=True)

# plt.savefig('tree.png', dpi=1200)


0.304
[[2 0 0 1 2 2 1 1 0 0]
 [4 4 1 2 0 0 0 0 2 1]
 [0 2 3 2 0 1 1 0 1 0]
 [2 1 3 3 3 2 0 0 1 2]
 [4 1 2 4 2 1 1 0 4 1]
 [0 0 2 1 0 6 1 0 1 1]
 [1 1 1 1 1 1 5 0 2 1]
 [0 0 0 0 0 1 1 5 0 0]
 [0 0 2 1 1 2 0 0 3 0]
 [0 1 0 0 1 2 1 0 3 5]]
0.3420360032124738
